# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "s3-tf-state-tg-reorg"
    dynamodb_table = "dynamo-terraform-lock"
    encrypt        = true
    key            = "network/terraform.tfstate"
    region         = "us-east-1"
  }
}
